import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { auth } from "@/auth/auth";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/QueryClientProviders";
import { ThemeProvider } from "next-themes";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Slack",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${lato.variable}  antialiased`}>
        <ThemeProvider defaultTheme="system" attribute="class">

        <NextAuthProvider session={session}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextAuthProvider>
        <Toaster position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
